<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h3>Introduzca sus credenciales</h3>
    <form action="" method="POST">
    <label for="usuario">Usuario</label>
    <input type="text" name="usr" placeholder="">
</br>
    <label for="Contraseña">Contraseña</label>
    <input type="password" name="pswd" placeholder="">
</br>
    <input type="submit" name="login" value="entrar">
    </form>
</body>
</html>