<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Post</title>
</head>
<body>
    <h1>Crear artículo</h1>
    <form action="index.php" method="post">
        <label for="title">Titulo:</label>
        <input type="text" id="title" name="title">
        <br>
        <label for="text">Contenido:</label>
        <textarea id="text" name="text"></textarea>
        <br>
        <input type="submit" value="Guardar" name="Guardar">
    </form>
    <br>
    <a href="index.php?c=user&logout=1">Cerrar sesión</a>
</body>
</html>