<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $post->getTitle() ?></title>
</head>
<body>
    <?php
    echo "<h2>".$post->getTitle()."</h2>";
    echo "<p>".$post->getText()."</p>";
    echo "<p>Fecha: ".$post->getDatetime()."</p>";
    echo "<a href='index.php?c=post'>Volver</a>";
    ?>
</body>
</html>